package(default_visibility = ["//visibility:public"])

cc_library(
    name = "mqueue",
    srcs = ["mqueue.cc"],
    hdrs = ["mqueue.h"],
    deps = [
        "@spdlog"
    ],
)

cc_library(
    name = "ringbuffer",
    srcs = ["ringbuffer.cc"],
    hdrs = ["ringbuffer.h"],
    deps = [
        "@spdlog"
    ],
)
