cc_test(
  name = "ringbuffer",
  size = "small",
  srcs = ["ringbuffer_test.cc"],
  deps = [
    "//protocol/utils:ringbuffer",
    "@googletest//:gtest_main",
  ],
)

cc_test(
  name = "timer",
  srcs = ["timer_test.cc"],
  deps = [
    "//protocol/utils:timer",
    "@googletest//:gtest_main",
  ],
)

cc_test(
  name = "crc16",
  srcs = ["crc16_test.cc"],
  deps = [
    "//protocol/utils:crc16",
    "@googletest//:gtest_main",
  ],
)
