package(default_visibility = ["//visibility:public"])

cc_library(
    name = "datalink",
    srcs = [
        "datalink.cc",
    ],
    hdrs = [
        "datalink.h"
    ],
    deps = [
        "//source/backend",
    ],
)

cc_library(
    name = "application",
    srcs = [
        "application.cc",
    ],
    hdrs = [
        "application.h"
    ],
    deps = [],
)

cc_library(
    name = "presentation",
    srcs = [
        "presentation.cc",
    ],
    hdrs = [
        "presentation.h"
    ],
    deps = [],
)

cc_library(
    name = "transport",
    srcs = [
        "transport.cc",
    ],
    hdrs = [
        "transport.h"
    ],
    deps = [],
)
